## The functions in this file provide the following:
## makeCaheMatrix provides the means to get and set a matrix and its' inverse.
##
## cacheSolve creates the inverse of the specified matrix.
##
## This file uses the prototype template supplied in Rodger D. Peng's 
## Assignment2 respository which can be found at:
##   https://github.com/rdpeng/ProgrammingAssignment2
##
## Author: David Guinivere

## makeCacheMatrix returns a list of functions for setting and 
## retrieving matrix and it cached value.

makeCacheMatrix <- function(x = matrix()) {
        invcache <- NULL  ## Set cache to NULL
        
        ## Creates "special" mattrix with cache set to NULL
        set <- function(y) {
                ## Store matrix and NULL cache in parent environment
                x <<- y         
                invcache <<- NULL 
        }
        
        ## Return the matrix
        get <- function() x  
        
        ## Store matrix inverse (supplied) into cache in parent environment
        setcache <- function(cache) invcache <<- cache
        
        ## Return cached inverse matrix
        getcache <- function() invcache
        
        ## Return a list of the functions generated by this function
        list(set = set, get = get,
             setcache = setcache,
             getcache = getcache)
}


## Return the inverse of matrix x. 
##   Return the cache value of x if available,
##   otherwise compute the inverse of the matrix and store in cache

cacheSolve <- function(x, ...) {
        ## Retrive cached inverse matrix
        invcache <- x$getcache()
        if(!is.null(invcache)) {
                ## Since cached value is not NULL, display message
                ## and return cached value
                message("getting cached data")
                return(invcache)
        }
        
        srcmatrix <- x$get()
        ## Compute inverse of srcmatrix
        invcache <- solve(srcmatrix, ...)
        ## Store inverse in cache of "special" matrix
        x$setcache(invcache)
        
        ## Return matrix inverse
        invcache
}
